#!/bin/bash
### @DeedWark - 2019 ###
### Most useful dig in same script ###

function help {
	cat <<-EOF
MUDIG - Most Useful DIG commands in same script
Usage:  mudig [domain] [selector]
	
Example: mudig domain.com
         mudig domain.com protonmail

Use mudig -h / mudig --help / mudig help  to show this message
EOF
}

[[ $1 == "--help" ]] || [[ $1 == "-h" ]] || [[ $1 == "help" ]] || [[ -z $1 ]] && help && exit 0

domain=$1	#domain.com
selector=$2	#selector (ex:google)
dns=$(dig $domain +short)	#DNS
mx=$(dig mx $domain +short)	#MX
txt=$(dig txt $domain +short)	#TXT
dm=$(dig _dmarc.$domain TXT +short)	#DMARC
dk=$(dig $selector._domainkey.$domain TXT +short 2> /dev/null)	#DKIM
dkg=$(dig google._domainkey.$domain TXT +short)	#DKIM/wGoogle

bold='\e[0;0;1m' #bold
dlob='\e[0m'	 #reset bold

### DNS ###
if [ -z "$dns" ]; then
	echo -e "$bold DNS (A):$dlob\nNo DNS found\n"
else
	echo -e "$bold DNS (A):$dlob\n$dns\n"
fi
### MX ###
if [ -z "$mx" ]; then
	echo -e "$bold MX fields:$dlob\nNo MX found\n"
else
	echo -e "$bold MX fields:$dlob\n$mx\n"
fi
### TXT ###
if [ -z "$txt" ]; then
	echo -e "$bold TXT records:$dlob\nNo TXT found\n"
else
	echo -e "$bold TXT records:$dlob\n$txt\n"
fi
### DMARC ###
if [ -z "$dm" ]; then
	echo -e "$bold DMARC key:$dlob\nNo DMARC key found\n"
else
	echo -e "$bold DMARC key:$dlob\n$dm\n"
fi

echo -e "$bold DKIM key:$dlob"
### CHECK IF $SELECTOR IS EMPTY ###
if [ -z "$selector" ]; then
	echo -e "Add a selector (ex: domain.com selector)"
	echo -e "\nTry with Google as selector:\n$dkg"
fi

### DKIM ###
if [ -z "$dk" ] && [ -z "$dkg" ]; then
	echo -e "No DKIM key found\n"
else
	echo -e "$dk\n"
fi
#####END#####
